POST http://127.0.0.1:5000/categories
Content-Type: application/json

{
    "title":"Home decorations",
    "description":"lorem ipsum"
}

###

GET http://127.0.0.1:5000/categories
Content-Type: application/json
Token: 7382c082-9b25-4fdc-9efe-8a94eab6bad7-0c647709-a2ea-41b4-ba31-1c5dc7c4fe6a

{
    
}

###

PUT http://127.0.0.1:5000/categories
Content-Type: application/json

{
    "id":5,
    "title": "Home decorations",
    "description":"lorem ipsum"
}

###

DELETE http://127.0.0.1:5000/categories
Content-Type: application/json

{
    "id": 4
}


###

GET http://127.0.0.1:5000/categories/1